name: "Build"

on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:
    inputs:
      examplesRepo:
        description: '(For non-main Examples) Artemis repo'
        required: true
        default: 'apache/activemq-artemis'
        type: string
      examplesRepoBranch:
        description: '(For non-main Examples) Artemis branch'
        required: true
        default: 'main'
        type: string

env:
  ARTEMIS_REPO: ${{ inputs.examplesRepo || 'apache/activemq-artemis' }}
  ARTEMIS_BRANCH: ${{ inputs.examplesRepoBranch || 'main' }}

jobs:
  test:
    name: Verify Examples
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]

    steps:
      - uses: actions/checkout@v4
        with:
          path: activemq-artemis-examples

      - name: Cache Maven Local Repo
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository/
          key: ${{ runner.os }}-mvn-${{ hashFiles('activemq-artemis-examples/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-mvn-

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Checkout Artemis Repo (non-main Examples)
        if: ${{ (github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main') }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ARTEMIS_REPO }}
          ref: ${{ env.ARTEMIS_BRANCH }}
          path: activemq-artemis

      - name: Identify Artemis Version (non-main Examples)
        id: identify-artemis-version
        if: ${{ (github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main') }}
        run: |
          cd activemq-artemis
          CURRENT_ARTEMIS_BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current Artemis version: ${CURRENT_ARTEMIS_BUILD_VERSION}"
          echo "artemis-build-version=${CURRENT_ARTEMIS_BUILD_VERSION}" >> $GITHUB_OUTPUT

      - name: Build Artemis (non-main Examples)
        if: ${{ (github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main') }}
        run: |
          cd activemq-artemis
          mvn -s ../activemq-artemis-examples/.github/maven-settings.xml install -DskipTests -T1C

      - name: Identify Examples Version (non-main Examples)
        id: identify-examples-version
        if: ${{ (github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main') }}
        run: |
          cd activemq-artemis-examples
          CURRENT_EXAMPLES_BUILD_VERSION=$(grep -m 1 -Po '(?<=version>)[^<]+' pom.xml)
          echo "Current Examples version: ${CURRENT_EXAMPLES_BUILD_VERSION}"
          echo "examples-build-version=${CURRENT_EXAMPLES_BUILD_VERSION}" >> $GITHUB_OUTPUT

      - name: Set Examples Version to Artemis Version (non-main Examples)
        if: ${{ ((github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main')) && steps.identify-artemis-version.outputs.artemis-build-version != steps.identify-examples-version.outputs.examples-build-version }}
        run: |
          cd activemq-artemis-examples
          ./scripts/update-examples-version.sh ${{ steps.identify-artemis-version.outputs.artemis-build-version }}

      - name: Verify Examples
        run: |
          cd activemq-artemis-examples
          ./scripts/run-examples.sh

      - name: Clean Up Before Caching
        run: |
          rm -rf ~/.m2/repository/org/apache/activemq/tests
          rm -rf ~/.m2/repository/org/apache/activemq/examples
          if [ -d ~/.m2/repository/org/apache/activemq ]; then find ~/.m2/repository/org/apache/activemq -name "*-SNAPSHOT" -type d -prune -exec rm -r '{}' \; ; fi

  checks:
    name: Compile Check
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]

    steps:
      - uses: actions/checkout@v4
        with:
          path: activemq-artemis-examples

      - name: Cache Maven Local Repo
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository/
          key: ${{ runner.os }}-mvn-${{ hashFiles('activemq-artemis-examples/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-mvn-

      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Checkout Artemis Repo (non-main Examples)
        if: ${{ (github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main') }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ARTEMIS_REPO }}
          ref: ${{ env.ARTEMIS_BRANCH }}
          path: activemq-artemis

      - name: Identify Artemis Version (non-main Examples)
        id: identify-artemis-version
        if: ${{ (github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main') }}
        run: |
          cd activemq-artemis
          CURRENT_ARTEMIS_BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current Artemis version: ${CURRENT_ARTEMIS_BUILD_VERSION}"
          echo "artemis-build-version=${CURRENT_ARTEMIS_BUILD_VERSION}" >> $GITHUB_OUTPUT

      - name: Build Artemis (non-main Examples)
        if: ${{ (github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main') }}
        run: |
          cd activemq-artemis
          mvn -s ../activemq-artemis-examples/.github/maven-settings.xml install -DskipTests -T1C

      - name: Identify Examples Version (non-main Examples)
        id: identify-examples-version
        if: ${{ (github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main') }}
        run: |
          cd activemq-artemis-examples
          CURRENT_EXAMPLES_BUILD_VERSION=$(grep -m 1 -Po '(?<=version>)[^<]+' pom.xml)
          echo "Current Examples version: ${CURRENT_EXAMPLES_BUILD_VERSION}"
          echo "examples-build-version=${CURRENT_EXAMPLES_BUILD_VERSION}" >> $GITHUB_OUTPUT

      - name: Set Examples Version to Artemis Version (non-main Examples)
        if: ${{ ((github.event_name == 'pull_request' && github.base_ref != 'main') || (github.event_name != 'pull_request' && github.ref != 'refs/heads/main')) && steps.identify-artemis-version.outputs.artemis-build-version != steps.identify-examples-version.outputs.examples-build-version }}
        run: |
          cd activemq-artemis-examples
          ./scripts/update-examples-version.sh ${{ steps.identify-artemis-version.outputs.artemis-build-version }}

      - name: Build Examples
        run: |
          cd activemq-artemis-examples
          mvn -s .github/maven-settings.xml package -Prelease

      - name: Clean Up Before Caching
        run: |
          rm -rf ~/.m2/repository/org/apache/activemq/tests
          rm -rf ~/.m2/repository/org/apache/activemq/examples
          if [ -d ~/.m2/repository/org/apache/activemq ]; then find ~/.m2/repository/org/apache/activemq -name "*-SNAPSHOT" -type d -prune -exec rm -r '{}' \; ; fi
